name: "TypeScript Action"

description: "Example TypeScript Action"

author: "cions"

inputs:
  action:
    description: "action to perform"
    required: false
    default: "test-action"

  contexts:
    description: "Contexts to print"
    required: false
    default: "github,env,vars,job,jobs,steps,runner,secrets,strategy,matrix,needs,inputs"

  github-token:
    description: "GITHUB_TOKEN"
    required: false
    default: ${{ github.token }}

outputs:
  output:
    description: "Action output"

runs:
  using: node20
  pre: dist/pre.mjs
  main: dist/main.mjs
  post: dist/post.mjs
