name: "TypeScript Action"

description: "Example TypeScript Action"

author: "cions"

inputs:
  github-token:
    description: "GITHUB_TOKEN"
    required: false
    default: ${{ github.token }}

outputs:
  output:
    description: "Action output"

runs:
  using: node20
  main: dist/main.js
  pre: dist/pre.js
  post: dist/post.js
