name: 'Example TypeScript Action'
description: 'Getting started with TypeScript Actions'
author: 'cions'
inputs:
  github-token:
    description: 'GITHUB_TOKEN'
    required: false
    default: ${{ github.token }}
outputs:
  result:
    description: 'Action result'
runs:
  using: 'node12'
  main: 'dist/index.js'
