name: "Composite Run Steps Action"
description: "Example Composite Run Steps Action"
author: "cions"

inputs:
  input:
    description: "Action input"
    required: false
    default: "default value"

outputs:
  output:
    description: "Action output"
    value: ${{ steps.set-output.outputs.output }}

runs:
  using: composite
  steps:
  - name: Print environment variables
    uses: cions/actions-playground/.github/actions/typescript-action@master
    with:
      action: print-envvars
  - name: Print contexts
    uses: cions/actions-playground/.github/actions/typescript-action@master
    env:
      GITHUB_CONTEXT: ${{ toJSON(github) }}
      ENV_CONTEXT: ${{ toJSON(env) }}
      JOB_CONTEXT: ${{ toJSON(job) }}
      STEPS_CONTEXT: ${{ toJSON(steps) }}
      RUNNER_CONTEXT: ${{ toJSON(runner) }}
      STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      INPUTS_CONTEXT: ${{ toJSON(inputs) }}
    with:
      action: print-contexts
      contexts: github,env,job,steps,runner,strategy,matrix,inputs
  - id: set-output
    shell: bash
    run: echo "output=Composite Run Steps Action output" >> "${GITHUB_OUTPUT}"
