name: Docker

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      id: setup-buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and Push
      id: build
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le
        load: ${{ github.event_name == 'pull_request' }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository_owner }}/hello-world:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/hello-world:latest
        cache-to: type=inline
    - name: Inspect Image
      run: docker buildx imagetools inspect --raw ${{ steps.build.outputs.digest }}
    - name: Run container
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json >/dev/null
        sudo systemctl restart docker.service
        docker run --rm ghcr.io/${{ github.repository_owner }}/hello-world:latest
        docker run --rm --platform=linux/amd64 ghcr.io/${{ github.repository_owner }}/hello-world:latest
        docker run --rm --platform=linux/386 ghcr.io/${{ github.repository_owner }}/hello-world:latest
        docker run --rm --platform=linux/arm/v6 ghcr.io/${{ github.repository_owner }}/hello-world:latest
        docker run --rm --platform=linux/arm/v7 ghcr.io/${{ github.repository_owner }}/hello-world:latest
        docker run --rm --platform=linux/arm64 ghcr.io/${{ github.repository_owner }}/hello-world:latest
        docker run --rm --platform=linux/ppc64le ghcr.io/${{ github.repository_owner }}/hello-world:latest
