name: Dump Events

run-name: Dump Events (${{ github.event_name }})

on:
  branch_protection_rule:
    types:
    - created
    - edited
    - deleted
  check_run:
    types:
    - created
    - rerequested
    - completed
    - requested_action
  check_suite:
    types:
    - completed
  create:
  delete:
  deployment:
  deployment_status:
  discussion:
    types:
    - created
    - edited
    - deleted
    - transferred
    - pinned
    - unpinned
    - labeled
    - unlabeled
    - locked
    - unlocked
    - category_changed
    - answered
    - unanswered
  discussion_comment:
    types:
    - created
    - edited
    - deleted
  fork:
  gollum:
  issue_comment:
    types:
    - created
    - edited
    - deleted
  issues:
    types:
    - opened
    - edited
    - deleted
    - transferred
    - pinned
    - unpinned
    - closed
    - reopened
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - locked
    - unlocked
    - milestoned
    - demilestoned
  label:
    types:
    - created
    - edited
    - deleted
  merge_group:
    types:
    - checks_requested
  milestone:
    types:
    - created
    - closed
    - opened
    - edited
    - deleted
  page_build:
  project:
    types:
    - created
    - closed
    - reopened
    - edited
    - deleted
  project_card:
    types:
    - created
    - moved
    - converted
    - edited
    - deleted
  project_column:
    types:
    - created
    - updated
    - moved
    - deleted
  public:
  pull_request:
    types:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - closed
    - reopened
    - synchronize
    - converted_to_draft
    - locked
    - unlocked
    - enqueued
    - dequeued
    - milestoned
    - demilestoned
    - ready_for_review
    - review_requested
    - review_request_removed
    - auto_merge_enabled
    - auto_merge_disabled
    branches:
    - "**"
    # branches-ignore: []
    paths:
    - "**"
    # paths-ignore: []
  pull_request_review:
    types:
    - submitted
    - edited
    - dismissed
  pull_request_review_comment:
    types:
    - created
    - edited
    - deleted
  pull_request_target:
    types:
    - assigned
    - unassigned
    - labeled
    - unlabeled
    - opened
    - edited
    - closed
    - reopened
    - synchronize
    - converted_to_draft
    - ready_for_review
    - locked
    - unlocked
    - review_requested
    - review_request_removed
    - auto_merge_enabled
    - auto_merge_disabled
    branches:
    - "**"
    # branches-ignore: []
    paths:
    - "**"
    # paths-ignore: []
  push:
    branches:
    - "**"
    # branches-ignore: []
    tags:
    - "**"
    # tags-ignore: []
    paths:
    - "**"
    # paths-ignore: []
  registry_package:
    types:
    - published
    - updated
  release:
    types:
    - published
    - unpublished
    - created
    - edited
    - deleted
    - prereleased
    - released
  repository_dispatch:
    types:
    - custom
  schedule:
  - cron: "35 9 25 * *"  # 25th of every month at 9:35 UTC
  status:
  watch:
    types:
    - started
  workflow_call:
    inputs:
      string:
        type: string
        description: "string input"
        required: false
        default: "default value"
      number:
        type: number
        description: "number input"
        required: false
      boolean:
        type: boolean
        description: "boolean input"
        required: false
    secrets:
      token:
        description: "secret token"
        required: false
    outputs:
      output:
        description: "workflow output"
        value: "value"
  workflow_dispatch:
    inputs:
      string:
        type: string
        description: "string input"
        required: true
        default: "default value"
      number:
        type: number
        description: "number input"
        required: false
      boolean:
        type: boolean
        description: "boolean input"
        required: false
      log-level:
        type: choice
        options:
        - debug
        - info
        - warn
        - error
        description: "log level"
        required: true
        default: warn
      environment:
        type: environment
        description: "environment"
        required: false
  workflow_run:
    types:
    - completed
    - requested
    - in_progress
    workflows:
    - "Dump Virtual Environment"
    branches:
    - $default-branch
    # branches-ignore: []

permissions: {}

jobs:
  dump-events:
    name: Dump Events
    runs-on: ubuntu-latest
    steps:
    - name: Print environment variables
      uses: cions/actions-playground/.github/actions/dump-envvars@master
    - name: Print context informations
      uses: cions/actions-playground/.github/actions/dump-contexts@master
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
        ENV_CONTEXT: ${{ toJSON(env) }}
        VARS_CONTEXT: ${{ toJSON(vars) }}
        JOB_CONTEXT: ${{ toJSON(job) }}
        STEPS_CONTEXT: ${{ toJSON(steps) }}
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
        SECRETS_CONTEXT: ${{ toJSON(secrets) }}
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        NEEDS_CONTEXT: ${{ toJSON(needs) }}
        INPUTS_CONTEXT: ${{ toJSON(inputs) }}
    - name: Print event.json
      env:
        EVENT_JSON: ${{ github.event_path }}
      run: jq -CS '.' "${EVENT_JSON}"
