name: Hello Actions

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      manual-input:
        description: 'Input for manual dispatch'
        required: false
        default: 'undefined'

jobs:
  dump-vm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
        - windows-latest
        - macos-latest
        - ubuntu-16.04
        - ubuntu-18.04
        - ubuntu-20.04
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Print Environment Variables
      shell: pwsh
      run: |
        $FormatEnumerationLimit = -1
        Get-ChildItem Env: | Format-Table -AutoSize -Wrap | Out-String -Width 4096
    - name: Print PATH environment variable
      shell: pwsh
      run: |
        $env:PATH.Split([System.IO.Path]::PathSeparator) | Out-String -Width 4096
    - name: List available commands
      shell: pwsh
      run: >
        Get-Command -CommandType All |
        Sort-Object CommandType,Source,Name |
        Format-Table -AutoSize -Wrap |
        Out-String -Width 4096

  actions:
    runs-on: ubuntu-latest

    services:
      nginx:
        image: nginx:latest
        ports:
        - 8888:80
        volumes:
        - data:/data
        options: --cpus 1

    outputs:
      crs-output: ${{ steps.crsaction.outputs.result }}
      docker-output: ${{ steps.dockeraction.outputs.result }}
      ts-output: ${{ steps.tsaction.outputs.result }}
      run-output: ${{ steps.runaction.outputs.result }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: crsaction
      name: Composite Run Steps Action
      uses: ./.github/actions/composite-run-steps-action
    - id: dockeraction
      name: Docker Action 1
      uses: ./.github/actions/docker-action
    - name: Docker Action 2
      uses: docker://gcc:10
      with:
        args: gcc -dM -E -x c /dev/null
    - id: tsaction
      name: TypeScript Action
      uses: ./.github/actions/typescript-action
    - id: runaction
      name: Bash Action
      run: echo "::set-output name=result::Output from a Run Action%0AThis is a second line"
    - name: Print steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "${STEPS_CONTEXT}" | jq -CS '.'
    - name: Print job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "${JOB_CONTEXT}" | jq -CS '.'
    - name: Run docker version
      run: docker version
    - name: Run docker inspect
      run: docker container ls -q | xargs -rn1 docker container inspect
    - name: Use Services
      run: curl -sSfL http://localhost:8888/ | tee nginx.html
    - name: Upload an artifact
      uses: actions/upload-artifact@v2
      with:
        name: nginx
        path: nginx.html
    - name: PowerShell Core
      shell: pwsh
      run: Write-Output "Hello, PowerShell!"
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Python Shell
      shell: python
      run: |
        import sys, os
        print(sys.version)
        print('sys.executable:', sys.executable)
        print('sys.argv:', sys.argv)
        print('os.getcwd():', os.getcwd())
        print('sys.stdout.isatty():', sys.stdout.isatty())

  consumer:
    runs-on: ubuntu-latest
    needs: [actions]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download an artifact
      uses: actions/download-artifact@v2
      with:
        name: nginx
    - name: Print an artifact
      run: cat nginx.html
    - name: Print needs context
      env:
        NEEDS_CONTEXT: ${{ toJSON(needs) }}
      run: echo "${NEEDS_CONTEXT}" | jq -CS '.'

  container:
    runs-on: ubuntu-latest

    container:
      image: docker:stable
      ports:
      - 8888:80
      volumes:
      - data:/data
      options: --cpus 2

    services:
      nginx:
        image: nginx:latest
        ports:
        - 80:80
        volumes:
        - data:/data
        options: --cpus 1

    defaults:
      run:
        shell: bash

    steps:
    - name: Install packages
      shell: sh
      run: apk add --no-cache bash curl git jq
    - name: Print environment variables
      run: typeset -px
    - name: Print job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "${JOB_CONTEXT}" | jq -CS '.'
    - name: Run docker version
      run: docker version
    - name: Run docker inspect
      run: docker container ls -q | xargs -rn1 docker container inspect
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use service container
      run: curl -sSfL http://nginx/
    - name: TypeScript Action
      uses: ./.github/actions/typescript-action
    - name: Docker Action
      uses: ./.github/actions/docker-action

  expression:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: testvals
      name: Set outputs
      uses: actions/github-script@v3
      with:
        script: |
          core.setOutput('array', '[{"name":"a"},{"name":"b"},{"name":"c"}]');
          core.setOutput('escape-test', 'foo" "bar');
    - name: Run expression tests
      env:
        VAL_NULL: ${{ null }}
        VAL_BOOLEAN: ${{ true }}
        VAL_INTEGER: ${{ 42 }}
        VAL_HEX: ${{ 0xDEADBEEF }}
        VAL_FLOAT: ${{ 3.141592653589793 }}
        VAL_SCIENTIFIC: ${{ 0.6022e24 }}
        VAL_STRING: ${{ 'hello world' }}
        VAL_ESCAPE_TEST: ${{ steps.testvals.outputs.escape-test }}
        VAL_MISSING_PROP1: ${{ toJSON(runner.missing) }}
        VAL_MISSING_PROP2: ${{ runner.missing }}
        VAL_MISSING_PROP3: ${{ runner.missing || 'missing' }}
        VAL_OBJFILTER1: ${{ toJSON(fromJson(steps.testvals.outputs.array).*.name) }}
        VAL_OBJFILTER2: ${{ toJSON(fromJson(steps.testvals.outputs.array).*.value) }}
        VAL_OBJFILTER3: ${{ toJSON(steps.*) }}
        VAL_OBJFILTER4: ${{ toJSON(steps.*.outputs) }}
        VAL_OBJFILTER5: ${{ toJSON(steps.*.outputs.*) }}
        VAL_HASHFILES: ${{ hashFiles('**') }}
      run: |
        echo -n 'NULL: '; jq -Ccn --args '$ARGS.positional' "${VAL_NULL}"
        echo -n 'BOOLEAN: '; jq -Ccn --args '$ARGS.positional' "${VAL_BOOLEAN}"
        echo -n 'INTEGER: '; jq -Ccn --args '$ARGS.positional' "${VAL_INTEGER}"
        echo -n 'HEX: '; jq -Ccn --args '$ARGS.positional' "${VAL_HEX}"
        echo -n 'FLOAT: '; jq -Ccn --args '$ARGS.positional' "${VAL_FLOAT}"
        echo -n 'SCIENTIFIC: '; jq -Ccn --args '$ARGS.positional' "${VAL_SCIENTIFIC}"
        echo -n 'STRING_DIRECT: '; jq -Ccn --args '$ARGS.positional' ${{ 'hello world' }}
        echo -n 'STRING_ENVVAR: '; jq -Ccn --args '$ARGS.positional' "${VAL_STRING}"
        echo -n 'ESCAPE_TEST_DIRECT: '; jq -Ccn --args '$ARGS.positional' "${{ steps.testvals.outputs.escape-test }}"
        echo -n 'ESCAPE_TEST_ENVVAR: '; jq -Ccn --args '$ARGS.positional' "${VAL_ESCAPE_TEST}"
        echo -n 'MISSING_PROP1: '; jq -Ccn --args '$ARGS.positional' "${VAL_MISSING_PROP1}"
        echo -n 'MISSING_PROP2: '; jq -Ccn --args '$ARGS.positional' "${VAL_MISSING_PROP2}"
        echo -n 'MISSING_PROP3: '; jq -Ccn --args '$ARGS.positional' "${VAL_MISSING_PROP3}"
        echo -n 'OBJFILTER1: '; jq -CSn --jsonargs '$ARGS.positional[]' "${VAL_OBJFILTER1}"
        echo -n 'OBJFILTER2: '; jq -CSn --jsonargs '$ARGS.positional[]' "${VAL_OBJFILTER2}"
        echo -n 'OBJFILTER3: '; jq -CSn --jsonargs '$ARGS.positional[]' "${VAL_OBJFILTER3}"
        echo -n 'OBJFILTER4: '; jq -CSn --jsonargs '$ARGS.positional[]' "${VAL_OBJFILTER4}"
        echo -n 'OBJFILTER5: '; jq -CSn --jsonargs '$ARGS.positional[]' "${VAL_OBJFILTER5}"
        echo -n 'HASHFILES: '; jq -Ccn --args '$ARGS.positional' "${VAL_HASHFILES}"

  failing-job-1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - run: exit 1
    - run: echo "on success"
      if: ${{ success() }}
    - run: echo "on failure"
      if: ${{ failure() }}
    - run: echo "on always"
      if: ${{ always() }}
    - name: Print job context
      if: ${{ always() }}
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "${JOB_CONTEXT}" | jq -CS '.'

  failing-job-2:
    runs-on: ubuntu-latest
    needs: failing-job-1
    steps:
    - name: Print needs context
      env:
        NEEDS_CONTEXT: ${{ toJSON(needs) }}
      run: echo "${NEEDS_CONTEXT}" | jq -CS '.'

  failing-job-3:
    runs-on: ubuntu-latest
    needs: failing-job-1
    if: ${{ needs.failing-job-1.result == 'success' }}
    steps:
    - name: Print needs context
      env:
        NEEDS_CONTEXT: ${{ toJSON(needs) }}
      run: echo "${NEEDS_CONTEXT}" | jq -CS '.'

  failing-job-4:
    runs-on: ubuntu-latest
    needs: failing-job-1
    if: ${{ needs.failing-job-1.result == 'failure' }}
    steps:
    - name: Print needs context
      env:
        NEEDS_CONTEXT: ${{ toJSON(needs) }}
      run: echo "${NEEDS_CONTEXT}" | jq -CS '.'

  failing-job-5:
    runs-on: ubuntu-latest
    needs: [failing-job-2, failing-job-3, failing-job-4]
    if: ${{ always() }}
    steps:
    - name: Print needs context
      env:
        NEEDS_CONTEXT: ${{ toJSON(needs) }}
      run: echo "${NEEDS_CONTEXT}" | jq -CS '.'
