name: Windows

on:
  push:
  pull_request:

jobs:
  docker:
    name: Docker for Windows
    runs-on: windows-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/windows-container:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run docker version
      run: docker version
    - name: Run docker info
      run: docker info
    - name: Login to GitHub Container Registry
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      run: docker login --username $Env:GITHUB_REPOSITORY_OWNER --password $Env:GHCR_TOKEN ghcr.io
    - name: Build Windows container
      run: docker build --tag $Env:IMAGE_NAME windows-container
    - name: Run windows container
      run: docker run --rm $Env:IMAGE_NAME
    - name: Push windows container
      run: docker push $Env:IMAGE_NAME
    - name: Run linux container
      continue-on-error: true
      run: |
        [Environment]::SetEnvironmentVariable("DOCKER_CLI_EXPERIMENTAL", "enabled")
        Write-Output "{\"experimental\":true}" | Out-File -FilePath "C:\ProgramData\docker\config\config.json" -Encoding utf8
        Restart-Service docker
        docker version
        docker run --rm --platform linux/amd64 ubuntu:latest cat /etc/os-release

  msvc:
    name: MSVC
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: vswhere -products *
    - run: vswhere -latest -products * -requires "Microsoft.VisualStudio.Component.VC.Tools.x86.x64" -property installationPath
    - run: Get-VSSetupInstance -All | ConvertTo-Json
    - name: Find Visual Studio installation
      run: |
        $installPath = (Get-VSSetupInstance -All | Select-VSSetupInstance -Latest -Product * -Require "Microsoft.VisualStudio.Component.VC.Tools.x86.x64").InstallationPath
        Write-Output "VSINSTALLPATH=$installPath" | Out-File -FilePath $Env:GITHUB_ENV -Append -Encoding utf8
    - name: Import Microsoft.VisualStudio.DevShell module
      run: |
        Import-Module -Name (Join-Path -Path $Env:VSINSTALLPATH -ChildPath "Common7\Tools\Microsoft.VisualStudio.DevShell.dll") -PassThru |
          Format-Table -AutoSize -Wrap
    - name: Run VsDevCmd.bat
      run: |
        $vsdevcmd = Join-Path -Path $Env:VSINSTALLPATH -ChildPath "Common7\Tools\VsDevCmd.bat"
        & $Env:COMSPEC /s /c """$vsdevcmd"" -arch=x64 -host_arch=x64 && set" | Where-Object {
          $_ -Match '^(\w+)=(.*)$'
        } | ForEach-Object {
          $Name, $Value = $Matches[1], $Matches[2]
          if ((-Not (Test-Path -Path Env:/$Name)) -OR ((Get-Item -Path Env:/$Name).Value -CNE $Value)) {
            [PSCustomObject]@{
              Name = $Name;
              Value = $Value -Replace [System.IO.Path]::PathSeparator, [System.Environment]::NewLine;
            }
            Write-Output "$Name=$Value" | Out-File -FilePath $Env:GITHUB_ENV -Append -Encoding utf8
          }
        } | Format-Table -AutoSize -Wrap | Out-String -Width ([Int32]::MaxValue-1) -Stream
    - name: List Visual Studio executables
      run: |
        Get-ChildItem -Path $Env:VSINSTALLDIR -Recurse |
          Where-Object Extension -In @($Env:PATHEXT.Split([System.IO.Path]::PathSeparator) + ".PS1") |
          ForEach-Object { $_.FullName.Replace($Env:VSINSTALLDIR, "") }
    - name: CMake project (Visual Studio 16 2019)
      run: |
        cmake -S hello-world -B build.msvc -G "Visual Studio 16 2019"
        cmake --build build.msvc --config Release --verbose
        ./build.msvc/Release/hello-c
        ./build.msvc/Release/hello-cpp
    - name: CMake project (Visual Studio 16 2019, with clang-cl)
      run: |
        cmake -S hello-world -B build.clang-cl -G "Visual Studio 16 2019" -T clangcl
        cmake --build build.clang-cl --config Release --verbose
        ./build.clang-cl/Release/hello-c.exe
        ./build.clang-cl/Release/hello-cpp.exe
    - name: CMake project (NMake)
      run: |
        cmake -S hello-world -B build.nmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build build.nmake --verbose
        ./build.nmake/hello-c.exe
        ./build.nmake/hello-cpp.exe
    - name: CMake project (Ninja)
      run: |
        cmake -S hello-world -B build.ninja -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        cmake --build build.ninja --verbose
        ./build.ninja/hello-c.exe
        ./build.ninja/hello-cpp.exe
    - name: Upload an artifact
      uses: actions/upload-artifact@v2
      with:
        name: msvc
        path: |
          build.*

  msys2:
    name: MSYS2

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: make msys2-devel cmake
    - name: Print Environment Variables
      run: typeset -px
    - name: Print predefined macros
      run: gcc -dM -E -x c /dev/null | sort
    - name: CMake project
      run: |
        cmake -S hello-world -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build build --verbose
        ./build/hello-c
        ./build/hello-cpp
    - name: Upload an artifact
      uses: actions/upload-artifact@v2
      with:
        name: msys2
        path: |
          build

  mingw64:
    name: MinGW64
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
    - name: Print Environment Variables
      run: typeset -px
    - name: Print predefined macros
      run: gcc -dM -E -x c /dev/null | sort
    - name: CMake project
      run: |
        cmake -S hello-world -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build build --verbose
        ./build/hello-c
        ./build/hello-cpp
    - name: Upload an artifact
      uses: actions/upload-artifact@v2
      with:
        name: mingw64
        path: |
          build

  wsl:
    name: WSL
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: wsl --help
    - name: Install Ubuntu 20.04
      run: |
        $ProgressPreference = "SilentlyContinue"
        Invoke-WebRequest -Uri https://aka.ms/wslubuntu2004 -OutFile .\Ubuntu.zip
        Expand-Archive -Path .\Ubuntu.zip -DestinationPath .\Ubuntu
        .\Ubuntu\ubuntu2004.exe install --root
    - run: wslconfig /list /all
    - name: Install packages
      shell: wsl bash --noprofile --norc -eo pipefail -c "$(t=""$(wslpath -au '{0}')""; sed -i 's/\r$//' ""$t""; echo ""$t"")"
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -qy --no-install-recommends build-essential cmake
    - run: wsl cat /etc/os-release
    - run: wsl typeset -px
    - name: Print predefined macros
      run: wsl bash -c 'gcc -dM -E -x c /dev/null | sort; true'
    - name: CMake project
      shell: wsl bash --noprofile --norc -eo pipefail -c "$(t=""$(wslpath -au '{0}')""; sed -i 's/\r$//' ""$t""; echo ""$t"")"
      run: |
        cmake -S hello-world -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
        cmake --build build --verbose
        ./build/hello-c
        ./build/hello-cpp
    - name: Upload an artifact
      uses: actions/upload-artifact@v2
      with:
        name: wsl
        path: |
          build
